worker : python main.py
worker : python map.py
worker : python npc.py
worker : python object_handler.py
worker : python object_rendered.py
worker : python pathfinding.py
worker : python player.py
worker : python raycasting.py
worker : python settings.py
worker : python sound.py
worker : python weapon.py
worker : python sprite_object.py
